---
- name: JDK 8 installation
  hosts: CENTOS
  become: true
  remote_user: root
  tasks:
    - name: Install package
      yum:
         name: /root/push/jdk-8u202-linux-x64.rpm
         state: present
 
